# Generated by Django 5.0.4 on 2025-07-02 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='fitness_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='studio.fitnessclass'),
        ),
    ]
